name: my-workflow

on: push

jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      # ...
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bun stup
        uses: oven-sh/setup-bun@v1

      - name: Run Super-linter
        uses: github/super-linter@v4

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun index.ts
      - run: bun test
      - run: bun run build
